### ISSUE TITLE
Wrong cursor position replaying above 1080p

### ISSUE THREAD

**Issue by kururu002** [Zuzu-Typ/Input-Recorder#1]
Hi, I'm trying to use this project to do some automation work. 
However, I found that when I replay the macros above 1920*1080 resolution (such as 4K), the program moves my cursor to the coordination at 1080p. 
For example, if I record a macro at 4K and move to (2000,1000), the replay then takes me to the bottom right-edge corner(which maximum).
Not sure if it's dll file constrain, but can you try to fix it? 
Thanks!

**Comment by Zuzu-Typ** [comment]
There is now an option to record input using "Relative coords".
That way they should scale to any resolution.
