### ISSUE TITLE
Mouse position wrong during playback

### ISSUE THREAD

**Issue by achimmihca** [Zuzu-Typ/Input-Recorder#4]
This project looks useful to me and very easy to use.

Sadly, the mouse position during playback differs from what I have recorded.
When clicking the play button then the mouse first jumps to a position more to the right and bottom than what I had recorded, as if there was a wrong offset.
It then moves in a similar same way as recorded, but still with a wrong offset.

I am on Windows 10 with 125% screen scale factor (screen size 2560x1440 pixels). Could this be an issue?

**Comment by Zuzu-Typ** [comment]
Hi there @achimmihca,

I'm currently working on a completely new version of this software. The "current" one has various flaws and in my opinion doesn't really work as a satisfactory macro recording solution.

The new version will have the option of editing the recorded macros or creating them completely from scratch.
It's not yet ready for release, but if you don't mind a few bugs here and there, I'd encourage you to [try it out](https://github.com/Zuzu-Typ/Input-Recorder/tree/version-2)!

Unfortunately, there is not currently any way of converting from the old macro format to the new one.

One thing to note: The main application (`Irec.py`) will save whatever the screen resolution was into the exported macro(s), however it currently ignores them during playback. What this means is that if you have recorded a macro in 800x600 resolution and moved from one edge of the screen to the other, and play it back on 1920x1080 resolution, it will also move from one edge of the screen to the other. It doesn't care about aspect ratios. It just uses relative screen coordinates (which you will see when in edit mode).

The player application (MacroPlayer.exe)  - which would be tough for you to build without any instructions which I have yet to write - is supposed to make the macros more useful. Currently it _doesn't_ use relative coordinates like the main application. Instead it uses the absolute coordinates stored in the macro. I.e. if you recorded at 800x600, moved from one edge of the screen to the other, and played it back at a higher resolution, it would still only move within the 800x600 area of the top left corner of the screen. 

This is just a temporary issue though, as the functionality to customize this just hasn't been created yet.

Anyway, hope you'll like it (:

**Comment by Zuzu-Typ** [comment]
Oh, and please make sure that you have the latest winput package installed. 
I just released version `1.3.0`, which fixes a few bugs.
If you don't have winput installed at all, running `Irec.py` will (or rather should) automagically install it.

It just won't update it if there is an older version installed.

This is really only relevant if you try to record mouse wheel or X-Button events.

**Comment by achimmihca** [comment]
Thanks! I tried version-2, but it has the same wrong offset.
I also tried another software called [Repeat](https://github.com/repeats/Repeat) (a Java project), but this has some other offset.
In an attempt to record my issue using [Screengun](https://github.com/jeffijoe/screengun), I noticed that the recorded screen area also has some other offset.

I don't know, maybe it is related to my RDP connection or the screen scaling factor in Windows?
I use a single monitor, in case this helps.

**Comment by Zuzu-Typ** [comment]
That's interesting.. Well the way that it works is that when recording, the application hooks into the windows message system via the user32.dll, which fires all sorts of events, including keyboard and mouse events.

The [mouse events](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-msllhookstruct) have an absolute [x and y coordinate](https://docs.microsoft.com/en-us/previous-versions/dd162805(v=vs.85)). That is stored and later played back exactly as recorded.
So if there is an offset, it must be either during the time of recording or during the time of playback.
I presume it's during the time of recording.

You could try this out with a short Python program:
```Python
import winput

def mouse_callback(event):
    print(event.position)

def capture_mouse():
    winput.hook_mouse(mouse_callback)
    
    try:
        while True:
             winput.get_message()
    except:
        winput.unhook_mouse()

print("Press CTRL+C to exit")
capture_mouse()
```

This will print the screen coordinates returned by Windows.

**Comment by Zuzu-Typ** [comment]
There is information about [DPI awareness](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/ne-shellscalingapi-process_dpi_awareness) mentioned in the mouse event description. This might be the culprit.
Though it still remains unclear, whether or not the problem lies on the recording or playback side of things.

**Comment by achimmihca** [comment]
Thanks for the quick response. It is working now 🚀 !

You did a good job, really nice and easy to use tool (in contrast ). Will use it to input repetitive stuff for testing.

Some remarks for the new version:

- playback is missing a way to exit. One can press escape to stop recording. The same should work for playback.
- a "delete a macro" button is missing
    - currently, macros are not persisted except when saved explicitly. I would prefer it the other way around: store macros that I record until I remove them
- macros are stored in a *.mcr file, which seems to be binary. I think it would be nice if this could be a JSON file instead such that the interested user can inspect and maybe edit the recording.

**Comment by Zuzu-Typ** [comment]
Hi @achimmihca,
 
I have now implemented the changes you requested, reworked the design, fixed some bugs and added or changed some features here and there.
I have also published the [MacroPlayer](https://github.com/Zuzu-Typ/Input-Recorder/releases/tag/2.0.0) application, which can be used to play back macros without any performance losses.
